[package]
name = "dia01"
version = "0.1.0"
authors = ["Eduardo Ismael Garcìa Pèrez <eduardo78d@gmail.com>"]
edition = "2018"

[[ bin ]]
name = "ecucacion" 
path = "src/ecucacion.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
